version: "3.3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elastic_springboot
    environment:
      - bootstrap.memory_lock=true
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - elastic
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana_springboot
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOST: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      - elastic
  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.0
    container_name: logstash_springboot
    volumes:
      - /opt/ELK/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /opt/ELK/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - elastic
    restart: always
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge

volumes:
  elastic_data:
    driver: local

